Repository taingo321/QuanLyCuaHangKFC, pull requests merged in 2023-11, with the labels that each got.

#27 Update Register Function
  .idea/misc.xml
  app/src/main/java/com/example/testorder/Fragment/AllFragment.java
  app/src/main/java/com/example/testorder/Fragment/GioHangFragment.java
  app/src/main/java/com/example/testorder/RegisterActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_register.xml
Labels: enhancement, update

#29 Pass Unfinished Login Layout
  app/src/main/res/drawable/bogocbutton.xml
  app/src/main/res/drawable/kfc1.png
  app/src/main/res/drawable/khung.xml
  app/src/main/res/drawable/nen.xml
  app/src/main/res/drawable/nenkfc.png
  app/src/main/res/layout/activity_main.xml
Labels: upgrading

#30 Update Login Function
  app/src/main/java/com/example/testorder/LoginActivity.java
  app/src/main/java/com/example/testorder/MainActivity.java
  app/src/main/java/com/example/testorder/Model/Users.java
  app/src/main/java/com/example/testorder/Prevalent/Prevalent.java
  app/src/main/java/com/example/testorder/ProfileActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_profile.xml
Labels: enhancement, update, upgrading

#32 Updating Product Categories
  app/src/main/java/com/example/testorder/AdminAddNewProductActivity.java
  app/src/main/java/com/example/testorder/AdminCategoryActivity.java
  app/src/main/java/com/example/testorder/Fragment/AllFragment.java
  app/src/main/java/com/example/testorder/HomeActivity.java
  app/src/main/res/drawable/brand_new_icon.png
  app/src/main/res/drawable/burger_icon.png
  app/src/main/res/drawable/combo_icon.png
  app/src/main/res/drawable/drinks_icon.png
  app/src/main/res/drawable/fried_chicken_icon.png
  app/src/main/res/drawable/snack_icon.png
  app/src/main/res/drawable/special_offers_icon.png
  app/src/main/res/layout/activity_admin_category.xml
  app/src/main/res/layout/fragment_all.xml
  app/src/main/res/layout/fragment_ga_ran.xml
Labels: upgrading

#35 Update Product Categories for sliding
  app/src/main/java/com/example/testorder/Fragment/AllFragment.java
  app/src/main/java/com/example/testorder/Fragment/BurgerFragment.java
  app/src/main/java/com/example/testorder/Fragment/GaRanFragment.java
  app/src/main/java/com/example/testorder/Fragment/ThucUongFragment.java
  app/src/main/res/layout/fragment_all.xml
  app/src/main/res/layout/fragment_burger.xml
  app/src/main/res/layout/fragment_ga_ran.xml
  app/src/main/res/layout/fragment_thuc_uong.xml
Labels: enhancement, update

#37 Fix actvity main and activity login
  app/src/main/res/drawable/background_black_1.xml
  app/src/main/res/drawable/background_black_2.xml
  app/src/main/res/drawable/bogocbutton.xml
  app/src/main/res/drawable/password_icon.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/rounded_button_2.xml
  app/src/main/res/drawable/user_icon.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_all.xml
  app/src/main/res/layout/fragment_burger.xml
  app/src/main/res/layout/fragment_ga_ran.xml
  app/src/main/res/layout/fragment_thuc_uong.xml
  app/src/main/res/layout/product_items_layout.xml
  app/src/main/res/values/colors.xml
Labels: bug, update

#40 Fix Activity cart,Activity admin new order,Cart item layout
  app/src/main/res/drawable/bogocbutton_2.xml
  app/src/main/res/drawable/nen_2.xml
  app/src/main/res/drawable/nenkfc2.jpg
  app/src/main/res/layout/activity_admin_new_orders.xml
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/cart_items_layout.xml
Labels: update
